using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Euler
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with and , the first terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,..
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public static class EvenFibonacciNumbers
    {
        public static int GetSumOfEvenNumbers(int limit= 4000000)
        {
            int sum = 0;
            int first = 1;
            int second = 2;

            if (second % 2 == 0)
            {
                sum += second;
            }
            while (second < limit)
            {
                //find the even number
                if(second % 2 == 0)
                {
                    sum += second;
                }
                int next = first + second;
                first = second;
                second= next;
            }
            return sum;
        }
    }
}
